[package]
name = "arkley_algebra"
documentation = "https://docs.rs/arkley_algebra"
repository = "https://github.com/Deaths-Door/arkley/tree/main/arkley_algebra"
version.workspace = true
edition.workspace = true
readme.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true

[features]
default = ["parse","equation"]
parse = ["num-notation/nom"]
equation = []

[dependencies]
num-notation = { version = "0.1.3" , features = ["num"] }
nom = "7.1.3"

strum = { version = "0.25", features = ["derive"] }
