[package]
name = "arkley_algebra"
documentation = "https://docs.rs/arkley_algebra"
repository = "https://github.com/Deaths-Door/arkley/tree/main/arkley_algebra"
version.workspace = true
edition.workspace = true
readme.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true

[features]
# TODO : Remove equation / describe from default feature
default = ["parse","function","equation","describe"] 
parse = ["num-notation/nom"]
equation = []
function = []

describe = ["arkley_describe"]

[dependencies]
num-notation = { version = "0.1.3" , features = ["num","hash"] }
nom = "7.1.3"

strum = { version = "0.25", features = ["derive"] }

arkley_describe = { workspace = true , optional = true }

[dev-dependencies]
concat-idents = "1.1.5"