[package]
name = "arkley_algebra"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arkley_numerics = { path = "../arkley_numerics" }
arkley_traits = { path = "../arkley_traits" }
